from django.db import models

class Product(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=255)
    sku = models.CharField(max_length=255, unique=True)
    url_scraped = models.TextField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    percent_discount = models.DecimalField(max_digits=5, decimal_places=2)
    price_discount = models.DecimalField(max_digits=10, decimal_places=4)
    tax = models.DecimalField(max_digits=10, decimal_places=4)
    price_included_taxes = models.DecimalField(max_digits=10, decimal_places=4)
    price_mt2 = models.DecimalField(max_digits=10, decimal_places=4, null=True, blank=True)
    price_mtl = models.DecimalField(max_digits=10, decimal_places=4, null=True, blank=True)
    stock_1 = models.IntegerField()
    stock_2 = models.IntegerField(null=True, blank=True)
    stock_3 = models.IntegerField(null=True, blank=True)
    stock_comentarie_1 = models.CharField(max_length=100, null=True, blank=True)
    stock_comentarie_2 = models.CharField(max_length=100, null=True, blank=True)
    stock_comentarie_3 = models.CharField(max_length=100, null=True, blank=True)
    images = models.TextField()  # Use JSONField if your database supports it (e.g., PostgreSQL, MySQL 5.7+)
    category = models.TextField(null=True, blank=True)
    route_product = models.TextField(null=True, blank=True)
    short_description = models.TextField(null=True, blank=True)
    long_description = models.TextField(null=True, blank=True)
    pdf = models.TextField(null=True, blank=True)
    length = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    width = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    height = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    weight = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    main_color = models.CharField(max_length=255, null=True, blank=True)
    glossy_or_matte = models.CharField(max_length=50, null=True, blank=True)
    main_material = models.CharField(max_length=255, null=True, blank=True)
    origen = models.CharField(max_length=255, null=True, blank=True)
    LastScrappeddate = models.DateTimeField(auto_now=True)
    Updateddate = models.DateTimeField(auto_now=True)
    Createddate = models.DateTimeField(auto_now_add=True)
    Status = models.CharField(max_length=50, null=True, blank=True)

    class Meta:
        db_table = 'product'
